### ISSUE TITLE
local variable 'numb' referenced before assignment

### ISSUE THREAD

**Issue by sleeplessKomodo** [klaspas/Letterboxd-top-friend-movies#1]
I set up a virtual python environment building python version 3.9.2 from source, installed the required dependencies, and ran 'main.py'. The script works to collect my username, and ask about users to exclude, but then after the "The number of rated movies is colleced..." text is displayed, the following error occurs:

```
/home/jimbo/bin/Letterboxd-top-friend-movies/main.py:321: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  movie_c = code.find(text="Ratings").parent["title"]
Traceback (most recent call last):
  File "/home/jimbo/bin/Letterboxd-top-friend-movies/main.py", line 497, in <module>
    lb.start()
  File "/home/jimbo/bin/Letterboxd-top-friend-movies/main.py", line 45, in start
    movie_count = get_movie_count(friends)
  File "/home/jimbo/bin/Letterboxd-top-friend-movies/main.py", line 329, in get_movie_count
    movie_count.append(int(numb))
UnboundLocalError: local variable 'numb' referenced before assignment
```

running `$ python --version` prints `Python 3.9.2`, so I know it's the version that should work. Not sure how to proceed, as I'm not to comfortable editing source code since I'm not that skilled with coding.

**Comment by sleeplessKomodo** [comment]
Ahh, so using chatGPT, I was able to fix the code. 

changing 

`code.find(text= . . . . .` 
to
`code.find(string=`

was the first step, then adding, 

`numb = 0` to line 317 fixes the `UnboundLocalError: local variable 'numb' referenced before assignment` error. 

just posting in case anyone else runs into this same issue!

**Comment by klaspas** [comment]
Fixed the problems now
